- name: Launch Frontend Server
  hosts: local
  connection: local
  user: root
  gather_facts: false
  
  vars: 
    keypair: jenkins-ansible
    security_group: Jenkins-Ansible
    instance_name: Jenkins-Ansible-CI-server-1
    instance_type: t1.micro
    image: ami-a73264ce
    instance_count: 1
    region: us-east-1
    
  user: jenkins
  tasks:
    - name: Launch frontend instances
      local_action: ec2 keypair={{keypair}} group={{security_group}} instance_type={{instance_type}} image={{image}} wait=true count={{instance_count}} region={{region}} instance_tags='{"Name":"Jenkins-Ansible-CI-server-1"}'
      register: ec2
     
    - name: Add all worker instance public IPs to host group
      local_action: add_host hostname={{item.public_ip}} groupname=launched ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/{{keypair}}.pem 
      with_items: ec2.instances
     
    - name: Create volumes and attach
      local_action: ec2_vol instance={{item.id}} volume_size=8 region={{region}} device_name=xvdf
      with_items: ec2.instances
      register: ec2_vol

    - name: Wait for ssh to come up
      local_action: wait_for host={{item.public_dns_name}} port=22 timeout=320 state=started
      with_items: ec2.instances
     
- name: Install and Prepare
  hosts: launched
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
   - common
   - upstart 
